### ISSUE TITLE
OpenOTP throws a "weak cryptographic parameters" error

### ISSUE THREAD

**Issue by rdubigny** [sunknudsen/totp#2]
Hi,

When I attempt to scan a QR code generated by the `generateUri` function with the OpenOTP app, I receive an error suggesting not to use this token.

I see no option to upgrade the algorithm. I suggest we hardcode the algorithm to SHA256 to maintain the simplicity of this package.

**Comment by rdubigny** [comment]
It turns out that the issue was due to the default length of the secret being set to 24. Changing it to 32 solves the problem.

(see: https://github.com/orgs/community/discussions/75936#discussioncomment-7727594)

**Comment by sunknudsen** [comment]
Hey @rdubigny,

Thanks for investigating issue.

Looks like issue is outside of the scope of this package.

If this is the case, can you please close https://github.com/sunknudsen/totp/pull/3?

Have a wonderful day,

Sun
